export const data = [
  {
    id: "blog-intro",
    title: "Blog Intro",
    category: "blog",
    icon: "FaBlog",
    iconBgClr: "#F1FAFF",
    description:
      "Looking to start a blog but not sure how to start? Use our blog intro tool to help you create a catchy and attention-grabbing intro for your first blog post!",
    tags: ["blog", "intro"],
    queryParams:
      "Give some explanation about the topic and then Show me the list of blog intro using following details",
    outputs: "10",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 200,
        required: true,
        title: "Write about your blog topic",
        id: "blog-title",
        queryParams: "Blog title",
      },
      {
        name: "input",
        type: "text",
        placeholder: "e.g. Creator",
        maxLength: 100,
        required: true,
        title: "Product / Service",
        id: "product/service",
        queryParams: "Product/Service",
      },
    ],
  },
  {
    id: "blog-body",
    title: "Blog Body",
    category: "blog",
    icon: "FaBlog",
    iconBgClr: "#F1FAFF",
    description:
      "The Blog Body Tool is here to help you get your blog up and running in no time. This easy-to-use tool will help you come up with ideas for what to write about.",
    queryParams: "Create blog body using following details",
    outputs: "1",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 400,
        required: true,
        title: "Write about your blog topic",
        id: "blog-title",
        queryParams: "Blog topic",
      },
      {
        name: "input",
        type: "text",
        placeholder: "e.g. Creator",
        maxLength: 100,
        required: true,
        title: "Brand / Company",
        id: "brand/company",
        queryParams: "Brand/Company",
      },
      {
        name: "input",
        type: "text",
        placeholder: "e.g. Creator",
        maxLength: 100,
        required: true,
        title: "Keywords",
        id: "keywords",
        queryParams: "Keywords",
      },
    ],
  },
  {
    id: "text-summarizer",
    title: "Text Summarizer",
    category: "blog",
    icon: "FaBlog",
    iconBgClr: "#F1FAFF",
    description: "Get the key points from a piece of text.",
    queryParams: "Summarize the description using following details",
    outputs: "1",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 500,
        required: true,
        title: "Your Text",
        id: "text-summarizer",
        queryParams: "Description",
      },
    ],
  },
  {
    id: "facebook-ad-title",
    title: "Facebook Ad Title",
    category: "digital ad",
    icon: "FcAdvertising",
    iconBgClr: "#F5F8FA",
    description:
      "Use the Facebook Ads Title Text Generator tool to create the perfect title for your next Facebook ad campaign. Just enter your keyword and the tool will generate dozens of title options for you to choose from.",
    queryParams:
      "Give some explanation about the topic and then Show me the list of facebook ad title using following details",
    outputs: "10",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 400,
        required: true,
        title: "Description",
        id: "description",
        queryParams: "Description",
      },
      {
        name: "input",
        type: "text",
        maxLength: 100,
        required: true,
        placeholder: "e.g. Creator",
        title: "Product / Service",
        id: "product/service",
        queryParams: "Product/Service",
      },
    ],
  },
  {
    id: "facebook-ad-text",
    title: "Facebook Ad Text",
    category: "digital ad",
    icon: "FcAdvertising",
    iconBgClr: "#F5F8FA",
    description:
      "If you're looking to create some killer Facebook ads, then you need to check out our Facebook Ad Text Tool. It's the perfect way to help create attention-grabbing, effective, and converting ad text.",
    queryParams:
      "Give some explanation about the topic and then Show me the list of facebook ad text using following details",
    outputs: "10",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 400,
        required: true,
        title: "Describe your product / service",
        id: "description",
        queryParams: "Description",
      },
      {
        name: "input",
        type: "text",
        maxLength: 100,
        required: true,
        placeholder: "e.g. Creator",
        title: "Product / Service",
        id: "product/service",
        queryParams: "Product/Service",
      },
    ],
  },
  {
    id: "google-ad-text",
    title: "Google Ad Text",
    category: "digital ad",
    icon: "FcAdvertising",
    iconBgClr: "#F5F8FA",
    description:
      "If you're looking to create some killer Google ads, then you need to check out our Google Ad Text Tool. It's the perfect way to help create attention-grabbing, effective, and converting ad text. ",
    queryParams:
      "Give some explanation about the topic and then Show me the list of google ad text using following details",
    outputs: "10",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 400,
        required: true,
        title: "Describe your product / service",
        id: "description",
        queryParams: "Description",
      },
      {
        name: "input",
        type: "text",
        maxLength: 100,
        required: true,
        placeholder: "e.g. Creator",
        title: "Product / Service",
        id: "product/service",
        queryParams: "Product/Service",
      },
    ],
  },
  {
    id: "amazon-product-description",
    title: "Amazon Product Description",
    category: "ecommerce",
    icon: "BsFillCartCheckFill",
    iconBgClr: "#FFF8DD",
    description: "Create compelling product descriptions for Amazon listings.",
    queryParams: "Create product description using following details",
    outputs: "1",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 400,
        required: true,
        title: "Key Benefits/ Features",
        id: "features",
        queryParams: "Features",
      },
      {
        name: "input",
        type: "text",
        maxLength: 100,
        required: true,
        placeholder: "e.g. Creator",
        title: "Product Name",
        id: "product-name",
        queryParams: "Product-Name",
      },
    ],
  },
  {
    id: "shopify-product-description",
    title: "Shopify Product Description",
    category: "ecommerce",
    icon: "BsFillCartCheckFill",
    iconBgClr: "#FFF8DD",
    description: "Create compelling product descriptions. ",
    queryParams: "Create shopify product description using following details",
    outputs: "1",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 400,
        required: true,
        title: "Key Benefits/ Features",
        id: "features",
        queryParams: "Features",
      },
      {
        name: "input",
        type: "text",
        maxLength: 100,
        required: true,
        placeholder: "e.g. Creator",
        title: "Product Name",
        id: "product-name",
        queryParams: "Product-Name",
      },
    ],
  },
  {
    id: "product-description",
    title: "Product Description",
    category: "ecommerce",
    icon: "BsFillCartCheckFill",
    iconBgClr: "#FFF8DD",
    description: "Create compelling product descriptions for your Ecommerce",
    queryParams: "Create product description using following details",
    outputs: "1",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 400,
        required: true,
        title: "Key Benefits/ Features",
        id: "features",
        queryParams: "Features",
      },
      {
        name: "input",
        type: "text",
        maxLength: 100,
        required: true,
        placeholder: "e.g. Creator",
        title: "Product Name",
        id: "product-name",
        queryParams: "Product-Name",
      },
    ],
  },
  {
    id: "photo-post-caption",
    title: "Photo Post Caption",
    category: "social media",
    icon: "FaUserCheck",
    iconBgClr: "#FFF5F8",
    description: "Write catchy captions for your photo posts.",
    queryParams:
      "Give some explanation about the topic and then Show me the list of photo post caption using following details",
    outputs: "10",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 300,
        required: true,
        title: "What is your post about?",
        id: "description",
        queryParams: "Description",
      },
    ],
  },
  {
    id: "pinterest-pin-title",
    title: "Pinterest Pin Title",
    category: "social media",
    icon: "FaUserCheck",
    iconBgClr: "#FFF5F8",
    description:
      "Create great Pinterest pin titles that drive engagement, traffic, and reach. ",
    queryParams:
      "Give some explanation about the topic and then Show me the list of pinterest pin title using following details",
    outputs: "10",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 300,
        required: true,
        title: "Tell us about the Pinterest Title",
        id: "description",
        queryParams: "Description",
      },
      {
        name: "input",
        type: "text",
        maxLength: 100,
        required: true,
        placeholder: "e.g. Creator",
        title: "Keywords",
        id: "keywords",
        queryParams: "Keywords",
      },
    ],
  },
  {
    id: "pinterest-description",
    title: "Pinterest Description",
    category: "social media",
    icon: "FaUserCheck",
    iconBgClr: "#FFF5F8",
    description:
      "Use short and catchy descriptions to help you get more engagement on your pins. ",
    queryParams: "Create pinterest description using following details",
    outputs: "1",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 400,
        required: true,
        title: "Tell us about the Pinterest Description",
        id: "description",
        queryParams: "Description",
      },
      {
        name: "input",
        type: "text",
        maxLength: 100,
        required: true,
        placeholder: "e.g. Creator",
        title: "Company Name",
        id: "company-name",
        queryParams: "Company-Name",
      },
      {
        name: "input",
        type: "text",
        maxLength: 100,
        required: true,
        placeholder: "e.g. Creator",
        title: "Keywords",
        id: "keywords",
        queryParams: "Keywords",
      },
    ],
  },
  {
    id: "youtube-video-title",
    title: "Youtube Video Title",
    category: "video",
    icon: "BsFillCameraVideoFill",
    iconBgClr: "#F8F5FF",
    description:
      "Create engaging, click-worthy titles for your videos that will rank on Youtube. Just enter your keywords and the tool will generate dozens of title options for you to choose from.",
    queryParams:
      "Give some explanation about the topic and then Show me the list of youtube video title using following details",
    outputs: "10",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 300,
        required: true,
        title: "What is the video about?",
        id: "description",
        queryParams: "Description",
      },
      {
        name: "input",
        type: "text",
        maxLength: 100,
        required: true,
        placeholder: "e.g. Creator",
        title: "Keywords to Rank for",
        id: "keywords",
        queryParams: "Keywords",
      },
    ],
  },
  {
    id: "youtube-video-description",
    title: "Youtube Video Description",
    category: "video",
    icon: "BsFillCameraVideoFill",
    iconBgClr: "#F8F5FF",
    description:
      "Create unique descriptions for Youtube videos that rank well in search Video",
    queryParams: "Create youtube video description using following details",
    outputs: "1",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 300,
        required: true,
        title: "What is your Video title?",
        id: "description",
        queryParams: "Description",
      },
      {
        name: "input",
        type: "text",
        maxLength: 100,
        required: true,
        placeholder: "e.g. Creator",
        title: "Keywords to Rank for",
        id: "keywords",
        queryParams: "Keywords",
      },
    ],
  },
  {
    id: "youtube-video-topic-idea",
    title: "Youtube Video Topic Idea",
    category: "video",
    icon: "BsFillCameraVideoFill",
    iconBgClr: "#F8F5FF",
    description:
      "Brainstorm new video topics that will engage viewers and rank well on YouTube. ",
    queryParams:
      "Give some explanation about the topic and then Show me the list of youtube video topic idea using following details",
    outputs: "10",
    inputs: [
      {
        name: "input",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 300,
        required: true,
        title: "What topic should the videos be about?",
        id: "description",
        queryParams: "Description",
      },
      {
        name: "input",
        type: "text",
        maxLength: 100,
        required: true,
        placeholder: "e.g. Creator",
        title: "Keywords to Rank",
        id: "keywords",
        queryParams: "Keywords",
      },
    ],
  },
  {
    id: "headline",
    title: "Headline",
    category: "writer",
    icon: "BsFillPencilFill",
    iconBgClr: "#E4E6EF",
    description:
      "Looking to create headlines that'll grab attention? Just enter in a few words related to what you want to write about, and our tool will generate a list of potential headlines for you to choose from.",
    queryParams:
      "Give some explanation about the topic and then Show me the list of headline using following details",
    outputs: "10",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 300,
        required: true,
        title: "Description",
        id: "description",
        queryParams: "Description",
      },
      {
        name: "input",
        type: "text",
        maxLength: 100,
        required: true,
        placeholder: "e.g. Creator",
        title: "Product / Service",
        id: "product/service",
        queryParams: "Product/Service",
      },
    ],
  },
  {
    id: "text-summary",
    title: "Text Summary",
    category: "writer",
    icon: "BsFillPencilFill",
    iconBgClr: "#E4E6EF",
    description:
      "This is a tool which can be used to summarize a text quickly and easily. It can be used to identify the main ideas and points in a text, and to create a concise summary of the key points.",
    queryParams: "Create text summary using following details",
    outputs: "1",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 400,
        required: true,
        title: "Which content do you want to summarize?",
        id: "description",
        queryParams: "Description",
      },
    ],
  },
  {
    id: "content-improve",
    title: "Content Improve",
    category: "writer",
    icon: "BsFillPencilFill",
    iconBgClr: "#E4E6EF",
    description:
      "This tool will help improve your text content by rewriting it for you. It will make sure that your text is error-free, well-written, and persuasive. ",
    queryParams: "Improve the content using following details",
    outputs: "1",
    inputs: [
      {
        name: "textarea",
        placeholder: "e.g. how AI will improve the future of product writing",
        type: "text",
        maxLength: 300,
        required: true,
        title: "Which content do you want to improve?",
        id: "description",
        queryParams: "Description",
      },
    ],
  },
];

export const planCards = [
  {
    id: 3,
    status: "active",
    uid: "7ecce79f-9b0a-48bd-b489-142d0fcba8a5",
    name: "Pro plan",
    tag: "Optimize",
    tagline: "Unleash the full potential of your business",
    features: "features",
    featured: 1,
    price: 200,
    selling_price: 100,
    currency: "usd",
    type: "credit_and_duration",
    duration: 365,
    credit: 1000,
    max_use: null,
    max_use_by_same_user: null,
    rdate: "2023-03-05T08:54:47.000Z",
    udate: "2023-03-05T08:54:47.000Z",
  },
  {
    id: 2,
    status: "active",
    uid: "49152c57-7307-4348-9ce1-086155b5cf7a",
    name: "Growth plan",
    tag: "Scale",
    tagline: "Take your business to the next level",
    features: "features",
    featured: 0,
    price: 130,
    selling_price: 65,
    currency: "usd",
    type: "credit_and_duration",
    duration: 365,
    credit: 500,
    max_use: null,
    max_use_by_same_user: null,
    rdate: "2023-03-05T08:53:44.000Z",
    udate: "2023-03-05T08:53:44.000Z",
  },
  {
    id: 1,
    status: "active",
    uid: "347c0296-5951-4e1e-a085-d79fdc87cb1f",
    name: "Starter plan",
    tag: "Launch",
    tagline: "Get started with the essentials",
    features: "features",
    featured: 0,
    price: 30,
    selling_price: 15,
    currency: "usd",
    type: "credit_and_duration",
    duration: 365,
    credit: 100,
    max_use: null,
    max_use_by_same_user: null,
    rdate: "2023-03-05T08:49:49.000Z",
    udate: "2023-03-05T08:49:49.000Z",
  },
];

export const answers = [
  {
    id: "blog-intro",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem laborum quisquam rem doloribus quasi. Numquam eius mollitia laborum tenetur reprehenderit, quam in accusamus amet dignissimos voluptates temporibus assumenda recusandae tempore. Officiis doloribus veniam aut quibusdam molestias, non tempore quia! Quasi pariatur ipsum eius tempora cum explicabo suscipit inventore dolorum ut ratione! Perferendis delectus, cum consectetur atque unde architecto illo modi ullam, sed fuga aut quidem nobis nisi cumque tempora. Distinctio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil dolor. Iure labore, voluptatem tempora non dicta animi natus. Qui, facilis voluptate id voluptatum necessitatibus voluptatibus, architecto dolore exercitationem tempora suscipit sit maxime esse optio tempore, ",
  },
  {
    id: "blog-body",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit impedit quo similique consequatur sapiente sint distinctio aperiam autem placeat eos error et libero iste voluptatum porro delectus modi, unde ipsa quibusdam ullam voluptates consectetur voluptas expedita! Qui numquam enim ab inventore a consectetur, aliquam veritatis odio excepturi voluptatibus laboriosam maiores expedita? Minima praesentium doloremque illo voluptate modi, ratione culpa dolorum tenetur veritatis! Tenetur tempore, accusantium provident a facere perferendis doloremque nemo enim. Aspernatur placeat reprehenderit architecto voluptatum unde nisi quaerat numquam? Architecto nesciunt minima ipsa porro quam asperiores cumque aperiam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil dolor. Iure labore, voluptatem tempora non dicta animi natus. Qui, facilis voluptate id voluptatum necessitatibus voluptatibus, architecto dolore exercitationem tempora suscipit sit maxime esse optio tempore, similique error! Deserunt doloribus temporibus blanditiis aliquam perferendis debitis excepturi repellendus, inventore eum laboriosam adipisci quidem odio minus dolor voluptas saepe illo magni autem nostrum? Modi dicta consectetur totam corporis rem error reiciendis optio qui provident dolor tempore asperiores laboriosam est deleniti, vitae veritatis quia molestias sapiente aperiam aliquid omnis! Iure ipsum fugiat sint iusto, eveniet officia, quisquam sapiente corrupti molestiae est itaque id sequi natus eius veritatis ab asperiores porro tenetur vel voluptate! Dolorem rem est animi magni itaque harum inventore possimus id maiores! Aliquid velit, saepe dicta sint dolores deserunt maxime consectetur corporis non nostrum. Debitis iste nemo optio velit, voluptas eveniet magni, ex temporibus nisi eum id nostrum veniam molestias quibusdam tempore dolor! Nostrum ab aliquid, est labore exercitationem ipsa. Quasi unde voluptate exercitationem.",
  },
  {
    id: "text-summarizer",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores quod eveniet animi nulla illo rem, repellat sequi dolorem laudantium minus quaerat debitis voluptatem tenetur magnam explicabo rerum fugiat tempora est velit cum praesentium officiis molestias libero? Accusantium ipsum ducimus ab inventore aspernatur deleniti consectetur laboriosam nulla id exercitationem quo, pariatur incidunt, repellendus consequuntur voluptatem veniam ad aut necessitatibus aperiam odit mollitia amet officiis ullam. Veritatis deleniti labore fugiat qui earum iure nostrum modi, atque quaerat impedit perferendis animi facilis temporibus libero non in laudantium alias pariatur asperiores facere ad a? Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil dolor. Iure labore, voluptatem tempora non dicta animi natus. Qui, facilis voluptate id voluptatum necessitatibus voluptatibus, architecto dolore exercitationem tempora suscipit sit maxime esse optio tempore, similique error!",
  },
  {
    id: "facebook-ad-title",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quae quo illo? Voluptas facilis odio cupiditate incidunt temporibus aliquid dolor ad impedit, voluptatum quam ratione sequi provident dignissimos possimus libero tempora consequatur aspernatur dolores quo? Tempore atque cumque, iusto vel, ab odio dolorem nobis, porro doloribus obcaecati pariatur autem! Voluptates eum velit ullam corrupti ut non neque quae asperiores esse eligendi ex, quasi impedit? Dolorum in repellendus esse voluptate consequatur sed perferendis error non facilis, neque delectus? Voluptate, neque. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae expli]ribus temporibus blanditiis aliquam perferendis debitis excepturi repellendus, inventore eum laboriosam adipisci quidem odio minus dolor voluptas saepe illo magni autem nostrum? Modi dicta consectetur totam corporis rem error reiciendis optio qui provident dolor tempore asperiores laboriosam est deleniti, vitae veritatis quia molestias sapiente aperiam aliquid omnis! Iure ipsum fugiat sint iusto, eveniet officia, quisquam sapiente corrupti molestiae est itaque id sequi natus eius veritatis ab asperiores porro tenetur vel voluptate! Dolorem rem est animi magni itaque harum inventore possimus id maiores! Aliquid velit, saepe dicta sint dolores deserunt maxime consectetur corporis non nostrum. Debitis iste nemo optio velit, voluptas eveniet magni, ex temporibus nisi eum id nostrum veniam molestias quibusdam tempore dolor! Nostrum ab aliquid, est labore exercitationem ipsa. Quasi unde voluptate exercitationem.",
  },
  {
    id: "facebook-ad-text",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur, quis quibusdam nesciunt molestiae accusamus unde magnam officia tempore odio totam itaque voluptatum a nemo adipisci eius suscipit possimus excepturi rerum facere, dolorem minus quo quod. Dolorem aut quae quasi laboriosam? Eaque sit magnam qui provident. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciend",
  },
  {
    id: "google-ad-text",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, cupiditate eius quos quia cumque sint dolorum minus. Mollitia accusamus cumque officiis dolorum minus blanditiis nesciunt ea corrupti, nihil consequatur, nulla corporis cupiditate alias labore earum numquam iste aliquid ratione. Suscipit a, blanditiis molestiae atque ipsa velit fuga aspernatur repellendus cupiditate soluta eos assumenda quia aliquid eaque aut ex magni ducimus nisi labore officiis! Neque optio mollitia itaque voluptatibus consequatur fuga voluptatem error corrupti dignissimos voluptas nostrum dicta quidem sapiente omnis quisquam culpa fugit, soluta saepe at amet. Ad, ipsum nemo non necessitatibus quidem aspernatur eius aut voluptatum nostrum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil dolor. Iure labore, voluptatem tempora non dicta animi natus. Qui, facilis voluptate id voluptatum necessitatibus voluptatibus, architecto dolore exercitationem tempora suscipit sit maxime esse optio tempore, similique error! Deserunt doloribus temporibus blanditiis aliquam perferendis debitis excepturi repellendus, inventore eum laboriosam adipisci quidem odio minus dolor voluptas saepe illo magni autem nostrum? Modi dicta consectetur totam corporis rem error reiciendis optio qui provident dolor tempore asperiores laboriosam est deleniti, vitae veritatis quia molestias sapiente aperiam aliquid omnis! Iure ipsum fugiat sint iusto, eveniet officia, quisquam sapiente corrupti molestiae est itaque id sequi natus eius veritatis ab asperiores porro tenetur vel voluptate! Dolorem rem est animi magni itaque harum inventore possimus id maiores! Aliquid velit, saepe dicta sint dolores deserunt maxime consectetur corporis non nostrum. Debitis iste nemo optio velit, voluptas eveniet magni, ex temporibus nisi eum id nostrum veniam molestias quibusdam tempore dolor! Nostrum ab aliquid, est labore exercitationem ipsa. Quasi unde voluptate exercitationem.",
  },
  {
    id: "amazon-product-description",
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore repellat illo itaque, odio mollitia odit minima tempora molestias placeat. Assumenda, est error in repudiandae earum vitae quasi unde maxime maiores? Quaerat placeat explicabo praesentium laudantium expedita ipsam quis eius cumque libero impedit, delectus sed quia mollitia distinctio enim, accusamus accusantium facilis adipisci quisquam natus quae qui! Neque esse quibusdam cupiditate modi id fugiat eos aspernatur. Officia suscipit quas quae numquam temporibus cupiditate eaque voluptas error impedit, dolorem hic necessitatibus nesciunt aspernatur quidem ad in odio animi repudiandae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil ",
  },
  {
    id: "shopify-product-description",
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore repellat illo itaque, odio mollitia odit minima tempora molestias placeat. Assumenda, est error in repudiandae earum vitae quasi unde maxime maiores? Quaerat placeat explicabo praesentium laudantium expedita ipsam quis eius cumque libero impedit, delectus sed quia mollitia distinctio enim, accusamus accusantium facilis adipisci quisquam natus quae qui! Neque esse quibusdam cupiditate modi id fugiat eos aspernatur. Officia suscipit quas quae numquam temporibus cupiditate eaque voluptas error impedit, dolorem hic necessitatibus nesciunt aspernatur quidem ad in odio animi repudiandae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil dolor. Iure labore, voluptatem tempora non dicta animi natus. Qui, facilis voluptate id voluptatum necessitatibus voluptatibus, architecto dolore exercitationem tempora suscipit sit maxime esse optio tempore, similique error! Deserunt doloribus temporibus blanditiis aliquam perferendis debitis excepturi repellendus, inventore eum laboriosam adipisci quidem odio minus dolor voluptas saepe illo magni autem nostrum? Modi dicta consectetur totam corporis r",
  },
  {
    id: "product-description",
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore repellat illo itaque, odio mollitia odit minima tempora molestias placeat. Assumenda, est error in repudiandae earum vitae quasi unde maxime maiores? Quaerat placeat explicabo praesentium laudantium expedita ipsam quis eius cumque libero impedit, delectus sed quia mollitia distinctio enim, accusamus accusantium facilis adipisci quisquam natus quae qui! Neque esse quibusdam cupiditate modi id fugiat eos aspernatur. Officia suscipit quas quae numquam temporibus cupiditate eaque voluptas error impedit, dolorem hic necessitatibus nesciunt aspernatur quidem ad in odio animi repudiandae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil dolor. Iure labore, voluptatem tempora non dicta animi natus. Qui, facilis voluptate id voluptatum necessitatibus voluptatibus, architecto dolore exercitationem tempora suscipit sit maxime esse optio tempore, similique error! ",
  },
  {
    id: "photo-post-caption",
    description:
      " Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi adipisci excepturi soluta modi dolorem explicabo similique enim quam ducimus autem in est, aperiam fugiat totam et facere quis quas minus, sit odio repudiandae voluptatem? Ab a officia harum repellat, ullam molestiae sed minima, nam ratione repudiandae consequatur consequuntur debitis reprehenderit quaerat quae non quia quos exercitationem! Ut, unde doloremque ratione quia cumque quod? Reiciendis libero qui itaque vitae doloribus. Iste enim facilis eligendi alias aspernatur quos labore dicta repellendus! Voluptates ducimus necessitatibus sed, delectus fugiat inventore nobis laborum ea architecto? Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil dolor. Iure labore, voluptatem tempora non dicta animi natus. Qui, facilis voluptate id voluptatum necessitatibus voluptatibus, architecto dolore exercitationem tempora suscipit sit maxime esse optio tempore, similique error! Deserunt doloribus temporibus blanditiis aliquam perferendis debitis excepturi repellendus, inventore eum laboriosam ",
  },
  {
    id: "pinterest-pin-title",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo, pariatur error veniam odio expedita, incidunt repellendus animi sapiente voluptatum vitae ab aut distinctio in. Sapiente, aut velit. Ipsam esse et, vero tempore consequatur optio quis. Minus minima, dolores nesciunt autem, quidem laudantium eum adipisci aspernatur corporis velit vitae neque nihil corrupti at itaque! Quod nisi rerum architecto exercitationem, eligendi repellat autem nemo odio pariatur aperiam culpa modi, eaque quia labore molestias sapiente eum provident animi a consectetur nihil! Eveniet cupiditate ipsam pariatur illo ducimus quibusdam ea labore ullam vel! Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil dolor. Iure labore, voluptatem tempora non dicta animi natus. Qui, facilis voluptate id voluptatum necessitatibus voluptatibus, architecto dolore exercitationem tempora suscipit sit maxime esse optio tempore, similique error! Deserunt doloribus temporibus blanditiis aliquam perferendis debitis excepturi repellendus, inventore eum laboriosam adipisci quidem odio minus dolor voluptas saepe illo magni autem nostrum? Modi dicta consectetur totam corporis r",
  },
  {
    id: "pinterest-description",
    description:
      " Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi adipisci excepturi soluta modi dolorem explicabo similique enim quam ducimus autem in est, aperiam fugiat totam et facere quis quas minus, sit odio repudiandae voluptatem? Ab a officia harum repellat, ullam molestiae sed minima, nam ratione repudiandae consequatur consequuntur debitis reprehenderit quaerat quae non quia quos exercitationem! Ut, unde doloremque ratione quia cumque quod? Reiciendis libero qui itaque vitae doloribus. Iste enim facilis eligendi alias aspernatur quos labore dicta repellendus! Voluptates ducimus necessitatibus sed, delectus fugiat inventore nobis laborum ea architecto? Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil dolor. Iure labore, voluptatem tempora non dicta animi natus. Qui, facilis voluptate id voluptatum necessitatibus voluptatibus, architecto dolore exercitationem tempora suscipit sit maxime esse optio tempore, similique error! Deserunt doloribus temporibus blanditiis aliquam perferendis debitis excepturi repellendus, inventore eum laboriosam adipisci quidem odio minus dolor voluptas saepe illo magni autem nostrum? Modi dicta consectetur totam corpori",
  },
  {
    id: "youtube-video-title",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio ad veritatis, inventore mollitia adipisci modi ut impedit dolore illum doloribus dolorem itaque architecto quasi tempora sint asperiores ducimus suscipit pariatur, eaque repudiandae obcaecati! Labore libero vel minus veritatis quis blanditiis eius ut tempora vero expedita dolores deserunt, similique harum laborum ipsum, obcaecati deleniti temporibus repudiandae necessitatibus enim. Aliquam, consectetur. Cum animi voluptate hic! Recusandae reiciendis molestias optio labore adipisci modi assumenda odio quae, vel soluta exercitationem velit quaerat corrupti blanditiis. Fugiat nostrum corrupti, repellendus odio odit atque repellat incidunt. Natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil dolor. Iure labore, voluptatem tempora non dicta animi natus. Qui, facilis voluptate id voluptatum necessitatibus voluptatibus, architecto dolore exercitationem tempora suscipit sit maxime esse optio tempore, similique error! Deserunt doloribus temporibus blanditiis aliquam perferendis debitis excepturi repellendus, inventore eum laboriosam adipisci quidem odio minus dolor voluptas saepe illo magni autem nostrum? Modi dicta consectetur totam corporis rem error ",
  },
  {
    id: "youtube-video-description",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt quisquam adipisci quis, at, quae velit laudantium illum saepe repellat quos provident obcaecati officia soluta reprehenderit, error facilis. Quasi recusandae ab aliquam sequi, fugit pariatur, repudiandae earum eum sed sit itaque culpa nisi id? Assumenda doloremque eaque cum praesentium distinctio natus magnam accusantium! Quos reiciendis, ut iste nesciunt distinctio nobis nam obcaecati atque minima, ullam quam iure nihil! Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil dolor. Iure labore, voluptatem tempora non dicta animi natus. Qui, facilis voluptate id voluptatum necessitatibus voluptatibus, architecto dolore exercitationem tempora suscipit sit maxime esse optio tempore, similique error! Deserunt doloribus temporibus blanditiis aliquam perferendis debitis excepturi repellendus, inventore eum laboriosam adipisci quidem odio minus dolor voluptas saepe illo magni autem nostrum? Modi dicta consectetur totam corporis rem error ",
  },
  {
    id: "youtube-video-topic-idea",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt quisquam adipisci quis, at, quae velit laudantium illum saepe repellat quos provident obcaecati officia soluta reprehenderit, error facilis. Quasi recusandae ab aliquam sequi, fugit pariatur, repudiandae earum eum sed sit itaque culpa nisi id? Assumenda doloremque eaque cum praesentium distinctio natus magnam accusantium! Quos reiciendis, ut iste nesciunt distinctio nobis nam obcaecati atque minima, ullam quam iure nihil! Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil dolor. Iure labore, voluptatem tempora non dicta animi natus. Qui, facilis voluptate id voluptatum necessitatibus voluptatibus, architecto dolore exercitationem tempora suscipit sit maxime esse optio tempore, similique error! Deserunt doloribus temporibus blanditiis aliquam perferendis debitis excepturi repellendus, inventore eum laboriosam adipisci quidem odio minus dolor voluptas saepe illo magni autem nostrum? Modi dicta consectetur totam corporis rem error reiciendis optio qui provident dolor tempore asperiores laboriosam est deleniti, vitae veritatis quia molestias sapiente aperiam aliquid omnis! Iure ipsum fugiat sint iusto, eveniet officia, quisquam sapiente corrupti molestiae est itaque id sequi natus eius veritatis ab asperiores porro tenetur vel voluptate! Dolorem rem est animi magni itaque harum inventore possimus id maiores! Aliquid velit, saepe dicta sint dolores deserunt maxime consectetur corporis non nostrum. Debitis iste nemo optio velit, voluptas eveniet magni, ex temporibus nisi eum id nostrum veniam molestias quibusdam tempore dolor! Nostrum ab aliquid, est labore exercitationem ipsa. Quasi unde voluptate exercitationem.",
  },
  {
    id: "headline",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt quisquam adipisci quis, at, quae velit laudantium illum saepe repellat quos provident obcaecati officia soluta reprehenderit, error facilis. Quasi recusandae ab aliquam sequi, fugit pariatur, repudiandae earum eum sed sit itaque culpa nisi id? Assumenda doloremque eaque cum praesentium distinctio natus magnam accusantium! Quos reiciendis, ut iste nesciunt distinctio nobis nam obcaecati atque minima, ullam quam iure nihil! Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil dolor. Iure labore, voluptatem tempora non dicta animi natus. Qui, facilis voluptate id voluptatum necessitatibus voluptatibus, architecto dolore exercitationem tempora suscipit sit maxime esse optio tempore, similique error! Deserunt doloribus temporibus blanditiis aliquam perferendis debitis excepturi repellendus, inventore eum laboriosam adipisci quidem odio minus dolor voluptas saepe illo magni autem nostrum? Modi dicta consectetur totam corporis rem error reiciendis optio qui provident dolor tempore asperiores laboriosam est deleniti, vitae veritatis quia molestias sapiente aperiam aliquid omnis! Iure ipsum fugiat sint iusto, eveniet officia, quisquam sapiente corrupti molestiae est itaque id sequi natus eius veritatis ab asperiores porro tenetur vel voluptate! Dolorem rem est animi magni itaque harum inventore possimus id maiores! Aliquid velit, saepe dicta sint dolores deserunt maxime consectetur corporis non nostrum. Debitis iste nemo optio velit, voluptas eveniet magni, ex temporibus nisi eum id nostrum veniam molestias quibusdam tempore dolor! Nostrum ab aliquid, est labore exercitationem ipsa. Quasi unde voluptate exercitationem.",
  },
  {
    id: "text-summary",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt quisquam adipisci quis, at, quae velit laudantium illum saepe repellat quos provident obcaecati officia soluta reprehenderit, error facilis. Quasi recusandae ab aliquam sequi, fugit pariatur, repudiandae earum eum sed sit itaque culpa nisi id? Assumenda doloremque eaque cum praesentium distinctio natus magnam accusantium! Quos reiciendis, ut iste nesciunt distinctio nobis nam obcaecati atque minima, ullam quam iure nihil Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eos eligendi nisi eaque tenetur, laudantium adipisci temporibus esse? Vel ea, nisi suscipit voluptate soluta reiciendis aperiam nemo illum et doloremque quaerat earum excepturi odio cupiditate pariatur sequi, qui mollitia esse nihil dolor. Iure labore, voluptatem tempora non dicta animi natus. Qui, facilis voluptate id voluptatum necessitatibus voluptatibus, architecto dolore exercitationem tempora suscipit sit maxime esse optio tempore, similique error! Deserunt doloribus temporibus blanditiis aliquam perferendis debitis excepturi repellendus, inventore eum laboriosam adipisci quidem odio minus dolor voluptas saepe illo magni autem nostrum? Modi dicta consectetur totam corporis rem error reiciendis optio qui provident dolor tempore asperiores laboriosam est deleniti, vitae veritatis quia molestias sapiente aperiam aliquid omnis! Iure ipsum fugiat sint iusto, eveniet officia, quisquam sapiente corrupti molestiae est itaque id sequi natus eius veritatis ab asperiores porro tenetur vel voluptate! Dolorem rem est animi magni itaque harum inventore possimus id maiores! Aliquid velit, saepe dicta sint dolores deserunt maxime consectetur corporis non nostrum. Debitis iste nemo optio velit, voluptas eveniet magni, ex temporibus nisi eum id nostrum veniam molestias quibusdam tempore dolor! Nostrum ab aliquid, est labore exercitationem ipsa. Quasi unde voluptate exercitationem.!",
  },
  {
    id: "content-improve",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt quisquam adipisci quis, at, quae velit laudantium illum saepe repellat quos provident obcaecati officia soluta reprehenderit, error facilis. Quasi recusandae ab aliquam sequi, fugit pariatur, repudiandae earum eum sed sit itaque culpa nisi id? Assumenda doloremque eaque cum praesentium distinctio natus magnam accusantium! Quos reiciendis, ut iste nesciunt distinctio nobis nam obcaecati atque minima, ullam quam iure nihil! Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt illo eius iure eveniet veniam animi, corporis voluptates optio earum dolores incidunt ducimus quos, natus quam vitae dicta quod numquam esse nulla eum dignissimos porro. Esse, voluptate possimus veniam blanditiis dicta aperiam totam vero aut temporibus unde dignissimos quia, dolorum labore laboriosam neque cumque est voluptatem repudiandae ipsa hic nam ipsam, animi consectetur! Quod vitae saepe necessitatibus beatae explicabo aperiam itaque amet, blanditiis odio sint? Voluptatum recusandae mollitia harum commodi in vel laudantium velit ut, alias quibusdam aliquid aliquam numquam deleniti iste iusto, quam aperiam nam. Dolorem quo distinctio explicabo quas molestias sint minus. Optio, animi. Ullam omnis minima, excepturi laboriosam iusto possimus sapiente est velit eoapiente aperiam aliquid omnis! Iure ipsum fugiat sint iusto, eveniet officia, quisquam sapiente corrupti molestiae est itaque id sequi natus eius veritatis ab asperiores porro tenetur vel voluptate! Dolorem rem est animi magni itaque harum inventore possimus id maiores! Aliquid velit, saepe dicta sint dolores deserunt maxime consectetur corporis non nostrum. Debitis iste nemo optio velit, voluptas eveniet magni, ex temporibus nisi eum id nostrum veniam molestias quibusdam tempore dolor! Nostrum ab aliquid, est labore exercitationem ipsa. Quasi unde voluptate exercitationem.",
  },
];
